//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyWatcher.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident
    {
        public int Accident_Id { get; set; }
        public string Accident_Description { get; set; }
        public Nullable<int> Situation_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public Nullable<double> Place_Lat { get; set; }
        public Nullable<double> Place_Long { get; set; }
        public string Place_Adress { get; set; }
    
        public virtual Situation Situation { get; set; }
        public virtual User_Data User_Data { get; set; }
        public virtual Actual_Status Actual_Status { get; set; }
    }
}
