//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyWatcher.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accident_Details()
        {
            this.Picture = new HashSet<Picture>();
        }
    
        public int Accident_Details_Id { get; set; }
        public int Accident_Id { get; set; }
        public Nullable<System.DateTime> Accident_Date { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Relation_Id { get; set; }
        public Nullable<double> Radius { get; set; }
    
        public virtual Accident Accident { get; set; }
        public virtual Relation Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Picture { get; set; }
    }
}
