//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyWatcher.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecologyWatchEntities1 : DbContext
    {
        public ecologyWatchEntities1()
            : base("name=ecologyWatchEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accident> Accident { get; set; }
        public virtual DbSet<Accident_Details> Accident_Details { get; set; }
        public virtual DbSet<Actual_Status> Actual_Status { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Relation> Relation { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<Situation> Situation { get; set; }
        public virtual DbSet<User_Auth> User_Auth { get; set; }
        public virtual DbSet<User_Data> User_Data { get; set; }
    }
}
