//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyWatcher.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Picture_Id { get; set; }
        public string Picture_Name { get; set; }
        public string Picture_Picture { get; set; }
        public Nullable<int> Accident_Details_Id { get; set; }
    
        public virtual Accident_Details Accident_Details { get; set; }
    }
}
