//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyWatcher.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Session_Id { get; set; }
        public Nullable<bool> Ok { get; set; }
        public Nullable<System.DateTime> Last { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public string Code { get; set; }
        public Nullable<int> User_Auth_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual User_Auth User_Auth { get; set; }
        public virtual User_Data User_Data { get; set; }
    }
}
