//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyWatcher.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Auth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Auth()
        {
            this.Session = new HashSet<Session>();
        }
    
        public int User_Auth_Id { get; set; }
        public string Auth_Source { get; set; }
        public string Auth_Value { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}
