//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcologyWatcher.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Data()
        {
            this.Accident = new HashSet<Accident>();
        }
    
        public int User_Id { get; set; }
        public string Login { get; set; }
        public string Password_Hash { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Joined_On { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accident> Accident { get; set; }
    }
}
